### ISSUE TITLE
Chapter https://pelux.io/software-factory/PELUX-3.0/swf-blueprint/docs/articles/sdk/configure-qtcreator.html

### ISSUE THREAD

**Issue by Shazter** [Pelagicore/software-factory-blueprint#156]
Special characters (`) in html version for 

https://pelux.io/software-factory/PELUX-3.0/swf-blueprint/docs/articles/sdk/configure-qtcreator.html

1. 

Wrong:
For the path of the compiler, use the results of the which `echo ${CC} | awk '{print $1}'` command ran in an SDK terminal

Correct:
For the path of the compiler, use the results of the which echo ${CC} | awk '{print $1}' command ran in an SDK terminal

2.

Wrong:
For the path of the compiler, use the result of the which `echo ${CXX} | awk '{print $1}'` command ran in an SDK terminal

Correct 
For the path of the compiler, use the result of the which echo ${CXX} | awk '{print $1}' command ran in an SDK terminal

**Comment by sashko** [comment]
Thank you for the clarifications. Would you mind making a PR as it's your finding?

**Comment by Shazter** [comment]
I try, first I have to figure out how to make pullrequest and how to test

**Comment by sashko** [comment]
> I try, first I have to figure out how to make pullrequest and how to test

No worries. Let us know if we can be of any help ;)
