### ISSUE TITLE
Remove "Bla bla" text from blueprint

### ISSUE THREAD

**Issue by rpannek** [Pelagicore/software-factory-blueprint#21]
In my opinion if we don't have something meaningfull written about a topic then we should not create any placeholder pages but instead just not have anything about it. Otherwise in the table of contents it looks like we have info but when you click on it it just says "Bla bla". One example is:

https://github.com/Pelagicore/software-factory-blueprint/blob/master/docs/articles/baseplatform/repo-manifests.rst

This should be removed.

**Comment by tobsan** [comment]
Or rather, it should be described properly. I'm on it.
