### ISSUE TITLE
meta-qt5 should only be in bblayers if building with QtAS

### ISSUE THREAD

**Issue by tobsan** [Pelagicore/software-factory-blueprint#24]
For some reason, meta-qt5 is in pelux-base.xml. It should be in pelux-qt.xml. The bblayers.conf should be updated accordingly, so that the layer is only included if building the QtAS version of PELUX

**Comment by DunderRoffe** [comment]
Wasn't this addressed in https://github.com/Pelagicore/meta-pelux/issues/31 which is now closed?
Furthermore, is software-factory-blueprint really the right place for this issue

**Comment by tobsan** [comment]
True, I must've been confused when creating this. The issue your referring to is boot2qt though, this is about meta-qt5. I'll move the issue to meta-pelux. Sorry for the fuzz.
