### ISSUE TITLE
Fix the formatting of the SDE chapter

### ISSUE THREAD

**Issue by GordanM** [Pelagicore/software-factory-blueprint#51]
There are some issues with the page where this is documented: http://pelux.io/software-factory/chapters/sde/index.html#software-development-environment. 

Like the dependency lines and one code block is wrongly formatted, etc.

**Comment by tobsan** [comment]
@GordanM can you have a look if this is still the case? I just checked the page and it looks fine I think.

**Comment by GordanM** [comment]
Looks good now!
